import React from 'react';

const QRCodePage = () => {
    // In a real scenario, this URL would be the deployed domain.
    // For now we use the local network or just a placeholder.
    const menuUrl = window.location.origin;

    return (
        <div style={{
            minHeight: '80vh',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            textAlign: 'center',
            padding: '2rem'
        }} className="fade-in">
            <h1 style={{ marginBottom: '2rem' }}>Scan to View Menu</h1>

            <div style={{
                background: 'white',
                padding: '2rem',
                borderRadius: '20px',
                boxShadow: '0 0 50px var(--accent-glow)'
            }}>
                {/* Placeholder for QR Code - typically generated by a library like qrcode.react */}
                {/* Using an API to generate for demonstration */}
                <img
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(menuUrl)}`}
                    alt="Menu QR Code"
                    style={{ width: '250px', height: '250px', display: 'block' }}
                />
            </div>

            <p style={{ marginTop: '2rem', color: 'var(--text-secondary)', maxWidth: '400px' }}>
                Open your camera and scan the code above to access the full digital menu of Prick Cafe.
            </p>
        </div>
    );
};

export default QRCodePage;
